# Site
name: 'Pinite'
description: 'Pinite is a free Jekyll theme for showcase, Pinterest like.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
disqus: 'demowebsite'
email: 'wowthemesnet@gmail.com'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page


# Syntax
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 20


# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]

# Header button
navbutton:
  btntitle: "Get Theme"
  btndes: "Get the theme for free"
  btnurl: "https://github.com/muhammedashfar7/Pinite"

# Menu
menu:
  - title: "Home"
    url: "/"
  - title: "Categories"
    url: "/categories"
  - title: "Posts"
    url: "/web-concepts-library"
  - title: "Contact"
    url: "/contact"

# Menu with Image or about
about:
  avatar: 'assets/images/sal.jpg'
  title: 'About'
  url: '/about'
# Social
facebook_username: "muhammed.ashfar.4"
github_username: "muhammedashfar7"
twitter_username: "ashfar_muhammed"
instagram_username: "b.lan.c"
