backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "assets/images"
collections:
  - label: "Site Settings"
    name: "settings"
    editor:
      preview: false
      delete: false
    files:
      - label: "Site Info"
        name: "site_info"
        file: "_config.yml"
        fields:
          - label: "Website Name"
            name: "name"
            widget: "string"
            required: true
          - label: "Description"
            name: "description"
            widget: "string"
            required: false
            hint: "This will show in search."
          - label: "Upload Logo"
            name: "logo"
            widget: "image"
            required: false
          - label: "Baseurl"
            name: "baseurl"
            widget: "string"
            required: false
            hint: "Name of folder where files are stored."
          - label: "Favicon"
            name: "favicon"
            widget: "image"
            required: true
          - label: "Avatar"
            name: "avatar"
            widget: "image"
            required: false
          - label: "Disqus Shortname"
            name: "disqus"
            widget: "string"
            required: true
            hint: "https://disqus_short.disqus.com"
          - label: "E-mail"
            name: "email"
            widget: "string"
            hint: "example@domain.com"
          - label: "Navigation Button"
            name: "navbutton"
            widget: "object"
            fields:
              - label: "Navigation Button Title"
                name: "btntitle"
                widget: "string"
                required: false
              - label: "Navigation Button Header"
                name: "btndes"
                widget: "string"
                hint: "Enter small headings for better view."
                required: false
              - label: "Navigation Button URL"
                name: "btnurl"
                widget: "string"
                hint: "https://yourdomain.com/"
                required: false
          - label: "Menu"
            name: "menu"
            widget: "list"
            required: false
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
                hint: "Text that will show up in the menu."
              - label: "URL"
                name: "url"
                widget: "string"
                hint: "Ex: /contact"
          - label: "About"
            name: "about"
            widget: "object"
            fields:
              - label: "Avatar"
                name: "avatar"
                widget: "image"
                required: false
              - label: "Title"
                name: "title"
                widget: "string"
                required: false
              - label: "URL"
                name: "url"
                widget: "string"
                required: false
                hint: "Ex: /about"
  - label: "Posts"
    name: "post"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "{{title}}"
    extension: "md"
    fields:
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD HH:mm:ss"
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "post"
      - label: "Post Title"
        name: "title"
        widget: "string"
        required: true
      - label: "Date and Author Info"
        name: "metadate"
        widget: "string"
        required: false
        hint: "hide for hiding or leave it blank."
      - label: "Categories"
        name: "categories"
        widget: "list"
        hint: "Each category is separated with comma."
      - label: "Post Image"
        name: "image"
        widget: "image"
        hint: "Try to add optimised image below 1MB. Makes site faster"
      - label: "Button URL"
        name: "visit"
        widget: "string"
        hint: "https://tagbit.tk/pintesero"
      - label: "Body"
        name: "body"
        widget: "markdown"
